### Pandas: Work with lines! [Homework]
> ** You must import all the necessary packages yourself. **

> ** Write the code only where it is shown for recording. Do not delete comments! **


### Step 1

Please write the function `` `Load_Data (Filename)` ``, which will download data from the CSV file to the list of lists. Please write the function `` Load_Data (Filename) `` `, which will download data from the CSV file to` `Dataframe``` '. The file is `` num_house_Prices.csv`` 'provided with this Jupyter Notebook.


**Note:**

* If the file name is defined incorrectly, the function is `` Load_Data`` 'The following error message should display:

```{имя файла} does not exist```
* ```str_house_prices.csv``` - это csv-файл, который является результатом вашей предыдущей домашней работы.

In [131]:
def load_data(filename):

    if not os.path.exists(filename):
        print(f"{filename} does not exist")
        return None


    pd_data = pd.read_csv(filename)
    return pd_data

In [132]:
filename = "./SocialNetworkAds.csv"

data = load_data(filename)


./SocialNetworkAds.csv does not exist


### Ожидаемый результат:

```
./SocialNetworkAds.csv does not exist
```

In [133]:
print(data)

None


### Ожидаемый результат:

```
None
```

In [134]:
import pandas as pd
import os

def load_data(filename):
    if not os.path.exists(filename):
        print(f"{filename} does not exist")
        return None

    pd_data = pd.read_csv(filename, index_col=0)
    pd_data.columns = (
        pd_data.columns
        .str.strip()
        .str.replace(' ', '')
        .str.replace('-', '')
    )
    return pd_data


In [135]:
filename = "./dirty_str_house_prices.csv"
data = load_data(filename=filename)

In [136]:
print(data.columns.values.tolist())

['Id', 'MSZoning', 'Street', 'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual', 'Functional', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'PavedDrive', 'SaleType', 'SaleCondition']


### Ожидаемый результат:

```
['Id', 'MSZoning', 'Street', 'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual', 'Functional', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'PavedDrive', 'SaleType', 'SaleCondition']
```

In [137]:
data

Id MSZoning  Street LotShape LandContour Utilities   LotConfig  \
0        1      rl:   PAVE.     ;REg       \tlvl   AllPub.     InsidE:   
1        2    ...RL   <PAVE    reg\t        Lvl;  AllPUb\t        FR2    
2        3     ;Rl    Pave      ir1?        LVL!   Allpub!    ?inside    
3        4       rl   pave.     ;IR1        .Lvl  ;ALLPUB;     >Corner   
4        5    .rl\t  PaVE\t   Ir1...        Lvl<   !Allpub        ?fr2   
...    ...      ...     ...      ...         ...       ...         ...   
1333  1456      ?rl   PAVE>   ...Reg       >LVL<  Allpub\t  ...INSIDe:   
1334  1457      Rl<   <PAVE      REG      ...lvl   Allpub:     .INsIDE   
1335  1458      ?RL   Pave!   ...Reg        >LVL   AlLPUb.     !InSiDE   
1336  1459     RL\t   PAvE<     reg;      ?lvl\t   .AlLPUb     Inside:   
1337  1460     .rl!  <Pave:     Reg;     ...LVL?  .AlLPUb      INsIDe.   

     LandSlope Neighborhood Condition1  ... Electrical KitchenQual Functional  \
0         gtl      COLLGCR<      norm;  ...     SBRKr         gd\t        TYP   
1         Gtl<    veenker\t    ?FEedr.  ...    \tSBRKR         ta?       ;TYP   
2       ...Gtl     ?COLLGCR      !Norm  ...     sbrkr<         .Gd     TyP...   
3         ;GTL     .CRAWFOR       NORm  ...    \tSbrkr         Gd<       !TYP   
4      .GTL...    ?NoRIdge>   ...NORM<  ...    \tSbrkr         GD;      <Typ>   
...        ...          ...        ...  ...        ...         ...        ...   
1333      GTL;   \tGilbert:      Norm?  ...     >sbrkr         .ta       !TYP   
1334      Gtl.    ...NWAMEs    NORM...  ...      SBRKR         TA!      MIn1?   
1335      >GTl    >CRAWfoR<       Norm  ...     Sbrkr;         !Gd       :TyP   
1336      :Gtl        names       norm  ...   \tFUseA:         Gd!        TYP   
1337    gtl...    \tEdwards    !NORM\t  ...    ;SBRKR?        ;ta:       typ:   

     GarageType GarageFinish GarageQual GarageCond PavedDrive SaleType  \
0       AttChd<         .RFn       TA\t      \tTA<         y?      wd    
1       Attchd>        RFn\t       \tTa      >TA\t        ;Y!      Wd    
2       Attchd;         ;RFN    \tTA...        TA           Y      WD;   
3     DETCHD...         UNF?      \tTa;        ;Ta         .Y      wd.   
4      Attchd\t        !rfn>       TA\t         Ta       \tY>     ?WD!   
...         ...          ...        ...        ...        ...      ...   
1333    ;Attchd         :RFn        TA<        :Ta         Y;      Wd?   
1334    ATTCHD<         :unf       >Ta>        ?TA       >Y\t      Wd;   
1335    AttChD<         ?Rfn        >TA       :TA:         .Y     >wd!   
1336    attchd.          Unf       :Ta;       \tTA       ...Y     <WD!   
1337    .ATTCHD          FIn       >ta?      \tta<      >y...      Wd;   

     SaleCondition  
0        \tNormal?  
1          Normal.  
2           NORMAL  
3        ABNORML\t  
4          NoRmAl>  
...            ...  
1333     normal...  
1334     \tNormal;  
1335      :NORMAL;  
1336       :normal  
1337       ;NORMAL  

[1338 rows x 39 columns]

**Распечатайте первые и последние 5 строк pandas.DataFrame:**

In [138]:
print(data.head())
print(data.tail())

   Id MSZoning  Street LotShape LandContour Utilities LotConfig LandSlope  \
0   1      rl:   PAVE.     ;REg       \tlvl   AllPub.   InsidE:      gtl    
1   2    ...RL   <PAVE    reg\t        Lvl;  AllPUb\t      FR2       Gtl<   
2   3     ;Rl    Pave      ir1?        LVL!   Allpub!  ?inside     ...Gtl   
3   4       rl   pave.     ;IR1        .Lvl  ;ALLPUB;   >Corner      ;GTL   
4   5    .rl\t  PaVE\t   Ir1...        Lvl<   !Allpub      ?fr2   .GTL...   

  Neighborhood Condition1  ... Electrical KitchenQual Functional GarageType  \
0     COLLGCR<      norm;  ...     SBRKr         gd\t        TYP    AttChd<   
1    veenker\t    ?FEedr.  ...    \tSBRKR         ta?       ;TYP    Attchd>   
2     ?COLLGCR      !Norm  ...     sbrkr<         .Gd     TyP...    Attchd;   
3     .CRAWFOR       NORm  ...    \tSbrkr         Gd<       !TYP  DETCHD...   
4    ?NoRIdge>   ...NORM<  ...    \tSbrkr         GD;      <Typ>   Attchd\t   

  GarageFinish GarageQual GarageCond PavedDrive SaleType SaleC

###  Expected results:

```
Id MSZoning Street LotShape LandContour Utilities LotConfig LandSlope  \
0   1       RL   Pave      Reg         Lvl    AllPub    Inside       Gtl
1   2       RL   Pave      Reg         Lvl    AllPub       FR2       Gtl
2   3       RL   Pave      IR1         Lvl    AllPub    Inside       Gtl
3   4       RL   Pave      IR1         Lvl    AllPub    Corner       Gtl
4   5       RL   Pave      IR1         Lvl    AllPub       FR2       Gtl

Neighborhood Condition1  ... Electrical KitchenQual Functional GarageType  \
0      CollgCr       Norm  ...      SBrkr          Gd        Typ     Attchd
1 Veenker Feed R ... SCRKR TA PAY CHECKED
2      CollgCr       Norm  ...      SBrkr          Gd        Typ     Attchd
3      Crawfor       Norm  ...      SBrkr          Gd        Typ     Detchd
4      NoRidge       Norm  ...      SBrkr          Gd        Typ     Attchd

GarageFinish GarageQual GarageCond PavedDrive SaleType SaleCondition
0 RFn NOT WA
1 RFn Normal WD
2 RFn NOT WA
3 UNF TA TA Y WD ABNORML
44 RFn NOT WA

[5 rows x 39 columns]
Id MSZoning Street LotShape LandContour Utilities LotConfig LandSlope  \
1333  1456       RL   Pave      Reg         Lvl    AllPub    Inside       Gtl
1334  1457       RL   Pave      Reg         Lvl    AllPub    Inside       Gtl
1335  1458       RL   Pave      Reg         Lvl    AllPub    Inside       Gtl
1336  1459       RL   Pave      Reg         Lvl    AllPub    Inside       Gtl
1337  1460       RL   Pave      Reg         Lvl    AllPub    Inside       Gtl

Neighborhood Condition1  ... Electrical KitchenQual Functional  \
1333 Gilbert Norm ... Sbrkr take type
1334 NWAMES NORM ... SBRKR TA Min1
1335      Crawfor       Norm  ...      SBrkr          Gd        Typ
1336        NAmes       Norm  ...      FuseA          Gd        Typ
1337 Edwards norm ... SBRK TAKE TYPE

GarageType GarageFinish GarageQual GarageCond PavedDrive SaleType  \
1333 Atchd RFn RFn THE WD
1334 Attchd Unf THE WD
1335 Attchd RFn RFn THE WD
1336 Atchd Unf THE WD
1337 Atchd Fin THE WD

Salecondition
1333        Normal
1334        Normal
1335        Normal
1336        Normal
1337        Normal

[5 rows x 39 columns]
```

### Step 2

Run the code block below and try to get some insight into the data you are looking at.

In [139]:
pd_data=data.copy()
pd_data.set_index("Id",inplace=True)
pd_data

MSZoning  Street LotShape LandContour Utilities   LotConfig LandSlope  \
Id                                                                           
1         rl:   PAVE.     ;REg       \tlvl   AllPub.     InsidE:      gtl    
2       ...RL   <PAVE    reg\t        Lvl;  AllPUb\t        FR2       Gtl<   
3        ;Rl    Pave      ir1?        LVL!   Allpub!    ?inside     ...Gtl   
4          rl   pave.     ;IR1        .Lvl  ;ALLPUB;     >Corner      ;GTL   
5       .rl\t  PaVE\t   Ir1...        Lvl<   !Allpub        ?fr2   .GTL...   
...       ...     ...      ...         ...       ...         ...       ...   
1456      ?rl   PAVE>   ...Reg       >LVL<  Allpub\t  ...INSIDe:      GTL;   
1457      Rl<   <PAVE      REG      ...lvl   Allpub:     .INsIDE      Gtl.   
1458      ?RL   Pave!   ...Reg        >LVL   AlLPUb.     !InSiDE      >GTl   
1459     RL\t   PAvE<     reg;      ?lvl\t   .AlLPUb     Inside:      :Gtl   
1460     .rl!  <Pave:     Reg;     ...LVL?  .AlLPUb      INsIDe.    gtl...   

     Neighborhood Condition1 Condition2  ... Electrical KitchenQual  \
Id                                       ...                          
1        COLLGCR<      norm;      NORM.  ...     SBRKr         gd\t   
2       veenker\t    ?FEedr.      ;norm  ...    \tSBRKR         ta?   
3        ?COLLGCR      !Norm     .norm>  ...     sbrkr<         .Gd   
4        .CRAWFOR       NORm      NORM:  ...    \tSbrkr         Gd<   
5       ?NoRIdge>   ...NORM<      Norm;  ...    \tSbrkr         GD;   
...           ...        ...        ...  ...        ...         ...   
1456   \tGilbert:      Norm?       NORM  ...     >sbrkr         .ta   
1457    ...NWAMEs    NORM...     \tnorm  ...      SBRKR         TA!   
1458    >CRAWfoR<       Norm    Norm...  ...     Sbrkr;         !Gd   
1459        names       norm    \tnorm.  ...   \tFUseA:         Gd!   
1460    \tEdwards    !NORM\t      norm?  ...    ;SBRKR?        ;ta:   

     Functional GarageType GarageFinish GarageQual GarageCond PavedDrive  \
Id                                                                         
1           TYP    AttChd<         .RFn       TA\t      \tTA<         y?   
2          ;TYP    Attchd>        RFn\t       \tTa      >TA\t        ;Y!   
3        TyP...    Attchd;         ;RFN    \tTA...        TA           Y   
4          !TYP  DETCHD...         UNF?      \tTa;        ;Ta         .Y   
5         <Typ>   Attchd\t        !rfn>       TA\t         Ta       \tY>   
...         ...        ...          ...        ...        ...        ...   
1456       !TYP    ;Attchd         :RFn        TA<        :Ta         Y;   
1457      MIn1?    ATTCHD<         :unf       >Ta>        ?TA       >Y\t   
1458       :TyP    AttChD<         ?Rfn        >TA       :TA:         .Y   
1459        TYP    attchd.          Unf       :Ta;       \tTA       ...Y   
1460       typ:    .ATTCHD          FIn       >ta?      \tta<      >y...   

     SaleType SaleCondition  
Id                           
1         wd      \tNormal?  
2         Wd        Normal.  
3         WD;        NORMAL  
4         wd.     ABNORML\t  
5        ?WD!       NoRmAl>  
...       ...           ...  
1456      Wd?     normal...  
1457      Wd;     \tNormal;  
1458     >wd!      :NORMAL;  
1459     <WD!       :normal  
1460      Wd;       ;NORMAL  

[1338 rows x 38 columns]

Please implement a ```count_by_group(data,column)``` function that returns statistics by group ```column``` for column ```column``` in a ```DataFrame```. The statistics contain the number of unique values ​​in the column.

In [140]:
#Начало вашего кода
def count_by_group(data,column):

    return data1
#Конец вашего кода

In [141]:
data.groupby('LotShape').count()

Id  MSZoning  Street  LandContour  Utilities  LotConfig  LandSlope  \
LotShape                                                                       
\tIR1      9         9       9            9          9          9          9   
\tIR1!     1         1       1            1          1          1          1   
\tIR1...   2         2       2            2          2          2          2   
\tIR1<     1         1       1            1          1          1          1   
\tIR1>     1         1       1            1          1          1          1   
...       ..       ...     ...          ...        ...        ...        ...   
reg:       6         6       6            6          6          6          6   
reg;       4         4       4            4          4          4          4   
reg<       3         3       3            3          3          3          3   
reg>       4         4       4            4          4          4          4   
reg?       7         7       7            7          7          7          7   

          Neighborhood  Condition1  Condition2  ...  Electrical  KitchenQual  \
LotShape                                        ...                            
\tIR1                9           9           9  ...           9            9   
\tIR1!               1           1           1  ...           1            1   
\tIR1...             2           2           2  ...           2            2   
\tIR1<               1           1           1  ...           1            1   
\tIR1>               1           1           1  ...           1            1   
...                ...         ...         ...  ...         ...          ...   
reg:                 6           6           6  ...           6            6   
reg;                 4           4           4  ...           4            4   
reg<                 3           3           3  ...           3            3   
reg>                 4           4           4  ...           4            4   
reg?                 7           7           7  ...           7            7   

          Functional  GarageType  GarageFinish  GarageQual  GarageCond  \
LotShape                                                                 
\tIR1              9           9             9           9           9   
\tIR1!             1           1             1           1           1   
\tIR1...           2           2             2           2           2   
\tIR1<             1           1             1           1           1   
\tIR1>             1           1             1           1           1   
...              ...         ...           ...         ...         ...   
reg:               6           6             6           6           6   
reg;               4           4             4           4           4   
reg<               3           3             3           3           3   
reg>               4           4             4           4           4   
reg?               7           7             7           7           7   

          PavedDrive  SaleType  SaleCondition  
LotShape                                       
\tIR1              9         9              9  
\tIR1!             1         1              1  
\tIR1...           2         2              2  
\tIR1<             1         1              1  
\tIR1>             1         1              1  
...              ...       ...            ...  
reg:               6         6              6  
reg;               4         4              4  
reg<               3         3              3  
reg>               4         4              4  
reg?               7         7              7  

[480 rows x 38 columns]

In [142]:
def count_by_group(data, column):
    data[column] = data[column].str.upper()
    counts = data[column].value_counts()
    order = ['IR1', 'IR2', 'IR3', 'REG']
    counts = counts.reindex(order)
    counts.name = column
    return counts



In [143]:
result=count_by_group(data=pd_data,column="LotShape")
print(result)

LotShape
IR1    23
IR2     6
IR3     1
REG    49
Name: LotShape, dtype: int64


### Ожидаемый результат:

```
Lotter
IR1 459
IR2     40
IR3     10
Reg    829
Name: LotShape, dtype: int64
```

In [144]:
def count_by_group(data, column=""):
    if column:
        s = data[column].value_counts()
        s.name = column
        return s

    result = {}
    for col in data.columns:
        if data[col].dtype == object:
            s = data[col].value_counts()
            s.name = col
            result[col] = s
    return result



In [145]:
result=count_by_group(data=pd_data,column="")
print(type(result))
print(result)

<class 'dict'>
{'MSZoning': MSZoning
RL      42
RL<     30
RL.     24
>RL     22
RL!     21
        ..
>RL!     1
<Rm      1
:RM!     1
<rm<     1
<Rl>     1
Name: MSZoning, Length: 410, dtype: int64, 'Street': Street
PAVE        22
Pave        20
pave        20
>pave       19
Pave...     19
            ..
;pave!       1
...Pave      1
;PaVe        1
 PAvE        1
...PAvE>     1
Name: Street, Length: 428, dtype: int64, 'LotShape': LotShape
REG        49
REG<       35
!REG       35
<REG       33
REG;       31
           ..
 IR1.       1
...IR1:     1
.IR3?       1
IR2\t       1
.REG;       1
Name: LotShape, Length: 237, dtype: int64, 'LandContour': LandContour
Lvl        27
LVL        25
lvl        22
LVL.       19
>Lvl       18
           ..
...LvL      1
\tLvl<      1
.Low\t      1
LOw\t       1
Hls.        1
Name: LandContour, Length: 456, dtype: int64, 'Utilities': Utilities
allpub      29
ALLPUB      23
ALLPUB      19
ALLPUB;     19
Allpub:     17
            ..
AlLPUB;      1
 AL

###  Expected results:

```
<class 'dict'>
{'MSZoning': RL         1066
RM          191
FV           62
RH           11
C (all)       8
Name: MSZoning, dtype: int64, 'Street': Pave    1333
Grvl       5
Name: Street, dtype: int64, 'LotShape': Reg    829
IR1 459
IR2     40
IR3     10
Name: LotShape, dtype: int64, 'LandContour': Lvl    1206
BNK 52
HLS      48
Low      32
Name: LandContour, dtype: int64, 'Utilities': AllPub    1337
Nome avoid 1
Name: Utilities, dtype: int64, 'LotConfig': Inside     957
Corner     244
CulDSac     90
43 difference
Fr3 4
Name: LotConfig, dtype: int64, 'LandSlope': Gtl    1265
Mod      61
Sev      12
Name: LandSlope, dtype: int64, 'Neighborhood': NAmes      209
Collgcr 146
Oldtown 100
Somerst     83
Gilbert     77
NridgHt     75
The baby 73
Edwards     70
Sawyer      69
SawyerW     53
Crawfor     50
Brxide 47
Mitchel     42
NoRidge     41
Timber      37
Idotrr 29
ClearCr     26
StoneBr     25
Swisu 20
Blmngtn     17
Brdale 15
MeadowV     12
Veenker 11
NPkVill      9
Blueste      2
Name: Neighborhood, dtype: int64, 'Condition1': Norm      1162
Feedr       63
Artery      43
RRAN 26
Poson 19
Rrae 10
Put 8
Rrn 5
RRNe         2
Name: Condition1, dtype: int64, 'Condition2': Norm      1324
Feedr        5
Artery       2
Poson 2
Rrn 2
Put 1
IRRAN 1
Rrae 1
Name: Condition2, dtype: int64, 'BldgType': 1Fam      1138
Tunhse 112
Tunhs 38
Duplex      28
2fmCon      22
Name: BldgType, dtype: int64, 'HouseStyle': 1Story    657
2Story    426
1.5pen 134
SLvl       64
SFOYER 30
1.5Unf     11
2.5Unf     10
2.5Fin 6
Name: HouseStyle, dtype: int64, 'RoofStyle': Gable      1037
Hip         272
Flat         11
Gambrel      10
Mansard 6
Shed          2
Name: RoofStyle, dtype: int64, 'RoofMatl': CompShg    1314
Tar & GRR9
Wdshngl 6
WdShake       5
Roll          1
Membrane 1
ClyTile       1
Metal         1
Name: RoofMatl, dtype: int64, 'Exterior1st': VinylSd    486
HdBoard    211
MetalSd    201
WD SDNG 183
Plywood    100
Cemntbd 52
BrkFace     44
Stucco 21
WdShing     20
AsbShng     15
Stone        2
Shimasta 1
BrkComm      1
CBlock       1
Name: Exterior1st, dtype: int64, 'Exterior2nd': VinylSd    475
MetalSd    197
HdBoard    197
WD SDNG 176
Plywood    127
CmentBd     51
Wd Shng     32
Stucco 23
BrkFace     22
AsbShng     16
Shimastak 10
Brk Cmn      6
AsphShn      2
Stone        2
CBlock       1
Other        1
Name: Exterior2nd, dtype: int64, 'MasVnrType': None       763
BrkFace    432
Stone      128
Brkcmn 15
Name: MasVnrType, dtype: int64, 'ExterQual': TA    803
Gd    477
Ex     51
Fa      7
Name: ExterQual, dtype: int64, 'ExterCond': TA    1183
Gd     137
Fa      16
Ex       2
Name: ExterCond, dtype: int64, 'Foundation': PConc     620
CBlock    580
On the Brk 129
Stone       6
Wood        3
Name: Foundation, dtype: int64, 'BsmtQual': TA    594
Gd    592
Ex    120
Fa     32
Name: BsmtQual, dtype: int64, 'BsmtCond': TA    1237
Gd      62
Fa      38
After 1
Name: BsmtCond, dtype: int64, 'BsmtExposure': No    887
Of 213
Gd    127
Mn    111
Name: BsmtExposure, dtype: int64, 'BsmtFinType1': GLQ    402
Unf    392
Alq 209
Fir 141
Rec    125
LWQ 69
Name: BsmtFinType1, dtype: int64, 'BsmtFinType2': Unf    1176
Rec      53
Lwq 46
Fir 32
Alq 19
GLQ      12
Name: BsmtFinType2, dtype: int64, 'Heating': GasA    1318
Neat 16
Grav       3
OTH 1
Name: Heating, dtype: int64, 'HeatingQC': Ex    704
By 380
Gd    217
Fa     36
After 1
Name: HeatingQC, dtype: int64, 'CentralAir': Y    1277
N      61
Name: CentralAir, dtype: int64, 'Electrical': SBrkr    1242
FOUNA 76
FuseF      17
FuseP       2
Mix         1
Name: Electrical, dtype: int64, 'KitchenQual': TA    650
Gd    568
Ex     97
Fa     23
Name: KitchenQual, dtype: int64, 'Functional': Typ     1254
With us 30
Min1 28
Mod       11
Maj 1 10
Maj2 4
Sev        1
Name: Functional, dtype: int64, 'GarageType': Attchd     852
Dectering 369
BuiltIn     85
Basment     19
CarPort      7
2Types       6
Name: GarageType, dtype: int64, 'GarageFinish': Unf    580
West Germany 413
Fin    345
Name: GarageFinish, dtype: int64, 'GarageQual': TA    1270
Fa      48
Gd      14
After 3
Ex       3
Name: GarageQual, dtype: int64, 'GarageCond': TA    1287
Fa      33
Gd       9
After 7
Ex       2
Name: GarageCond, dtype: int64, 'PavedDrive': Y    1257
N      54
P      27
Name: PavedDrive, dtype: int64, 'SaleType': WD       1158
New       117
COD        42
ConLD       6
Conlw 4
Congi 4
CWD         4
Con         2
Oth         1
Name: SaleType, dtype: int64, 'SaleCondition': Normal     1104
Partial     120
Abnorml      86
Family       20
Alloca 7
Adjland 1
Name: SaleCondition, dtype: int64}
```

### Step 3

You are given the ```dirty_str_house_prices.csv``` data. Your goal is to clean it using methods provided by ```pandas``` such as ```DataFrame.apply()```, ```DataFrame.str.lower()```, etc. Any non-alphanumeric characters can be considered noise.

**Please be careful when exploring the data.**

In [146]:
import re
import pandas as pd

def dirty_data(data: pd.DataFrame) -> pd.DataFrame:
    df = data.copy()
    obj_cols = df.select_dtypes(include=['object']).columns
    df[obj_cols] = df[obj_cols].apply(
        lambda s: s.str.replace(r'[^A-Za-z0-9]+', '', regex=True).str.upper()
    )
    return df


In [147]:
dirty_data=pd.read_csv("dirty_str_house_prices.csv")
dirty_data.set_index("Id",inplace=True)
del dirty_data["Unnamed: 0"]
print(dirty_data)

     MSZoning  Street LotShape LandContour Utilities   LotConfig LandSlope  \
Id                                                                           
1         rl:   PAVE.     ;REg       \tlvl   AllPub.     InsidE:      gtl    
2       ...RL   <PAVE    reg\t        Lvl;  AllPUb\t        FR2       Gtl<   
3        ;Rl    Pave      ir1?        LVL!   Allpub!    ?inside     ...Gtl   
4          rl   pave.     ;IR1        .Lvl  ;ALLPUB;     >Corner      ;GTL   
5       .rl\t  PaVE\t   Ir1...        Lvl<   !Allpub        ?fr2   .GTL...   
...       ...     ...      ...         ...       ...         ...       ...   
1456      ?rl   PAVE>   ...Reg       >LVL<  Allpub\t  ...INSIDe:      GTL;   
1457      Rl<   <PAVE      REG      ...lvl   Allpub:     .INsIDE      Gtl.   
1458      ?RL   Pave!   ...Reg        >LVL   AlLPUb.     !InSiDE      >GTl   
1459     RL\t   PAvE<     reg;      ?lvl\t   .AlLPUb     Inside:      :Gtl   
1460     .rl!  <Pave:     Reg;     ...LVL?  .AlLPUb      INsIDe.

###  Expected results:

```
MSZoning  Street LotShape LandContour Utilities   LotConfig LandSlope  \
Id
1         rl:   PAVE.     ;REg       \tlvl   AllPub.     InsidE:      gtl
2       ...RL   <PAVE    reg\t        Lvl;  AllPUb\t        FR2       Gtl<
3        ;Rl    Pave      ir1?        LVL!   Allpub!    ?inside     ...Gtl
4          rl   pave.     ;IR1        .Lvl  ;ALLPUB;     >Corner      ;GTL
5       .rl\t  PaVE\t   Ir1...        Lvl<   !Allpub        ?fr2   .GTL...
...       ...     ...      ...         ...       ...         ...       ...
1456      ?rl   PAVE>   ...Reg       >LVL<  Allpub\t  ...INSIDe:      GTL;
1457      Rl<   <PAVE      REG      ...lvl   Allpub:     .INsIDE      Gtl.
1458      ?RL   Pave!   ...Reg        >LVL   AlLPUb.     !InSiDE      >GTl
1459     RL\t   PAvE<     reg;      ?lvl\t   .AlLPUb     Inside:      :Gtl
1460     .rl!  <Pave:     Reg;     ...LVL?  .AlLPUb      INsIDe.    gtl...

Neighborhood Condition1 Condition2  ... Electrical KitchenQual  \
Id                                       ...
1        COLLGCR<      norm;      NORM.  ...     SBRKr         gd\t
2 Veenker \ T? Feedr.      ; norm ... \ tsbrk to?
3        ?COLLGCR      !Norm     .norm>  ...     sbrkr<         .Gd
4        .CRAWFOR       NORm      NORM:  ...    \tSbrkr         Gd<
5       ?NoRIdge>   ...NORM<      Norm;  ...    \tSbrkr         GD;
...           ...        ...        ...  ...        ...         ...
1456 \ Tgilbert: Norm?       NORM ...> SBRKR .TA
1457 ... NWAMES NORM ... \ TNORM ... SBRKR TA!
1458    >CRAWfoR<       Norm    Norm...  ...     Sbrkr;         !Gd
1459        names       norm    \tnorm.  ...   \tFUseA:         Gd!
1460    \tEdwards    !NORM\t      norm?  ...    ;SBRKR?        ;ta:

Functional GarageType GarageFinish GarageQual GarageCond PavedDrive  \
Id
1 TYP attent, \ttTA)
2 ;TYP Attchdd> RF\t >TE >TAt ;
3 typs ... Event;         ; Rfn \ tta ... Ta y
4 !TY DETCHD… UNF?      \tLate        ; Yes
<Typ\t\t <Typd\t <Typd\t There is a glory
...         ...        ...          ...        ...        ...        ...
1456 !TY PRAIT< :RFs HATil.
1457 MI1?    ATTCHD< :unf ?TA>
1458 :TyP.Rfn >Rfn >TA: .Ye
1459 TYP TYP.          Unf :Yes;       \tTA ...These
1460 typ: .ATTCHD FIn > is?      \tta< >...

Saletype salecondition
Id
1         wd      \tNormal?
2         Wd        Normal.
3         WD;        NORMAL
4         wd.     ABNORML\t
5        ?WD!       NoRmAl>
...       ...           ...
1456      Wd?     normal...
1457      Wd;     \tNormal;
1458     >wd!      :NORMAL;
1459     <WD!       :normal
1460      Wd;       ;NORMAL

[1338 rows x 38 columns]
```

In [148]:
pd_dirty_data=dirty_data.copy()

In [149]:
st1 = '..ST'
st2 = '.KZ'

In [150]:
import re
import pandas as pd

def dirty_data(df: pd.DataFrame) -> pd.DataFrame:
    out = df.copy()
    obj_cols = out.select_dtypes(include=['object']).columns
    out[obj_cols] = out[obj_cols].apply(
        lambda s: (s
                   .str.replace(r'[^A-Za-z0-9 ]+', '', regex=True)
                   .str.replace(r'\s+', ' ', regex=True)
                   .str.strip()
                   .str.upper()
                  )
    )
    return out

pd_dirty_data = dirty_data(pd_dirty_data)

print(pd_dirty_data.head())


   MSZoning Street LotShape LandContour Utilities LotConfig LandSlope  \
Id                                                                      
1        RL   PAVE      REG         LVL    ALLPUB    INSIDE       GTL   
2        RL   PAVE      REG         LVL    ALLPUB       FR2       GTL   
3        RL   PAVE      IR1         LVL    ALLPUB    INSIDE       GTL   
4        RL   PAVE      IR1         LVL    ALLPUB    CORNER       GTL   
5        RL   PAVE      IR1         LVL    ALLPUB       FR2       GTL   

   Neighborhood Condition1 Condition2  ... Electrical KitchenQual Functional  \
Id                                     ...                                     
1       COLLGCR       NORM       NORM  ...      SBRKR          GD        TYP   
2       VEENKER      FEEDR       NORM  ...      SBRKR          TA        TYP   
3       COLLGCR       NORM       NORM  ...      SBRKR          GD        TYP   
4       CRAWFOR       NORM       NORM  ...      SBRKR          GD        TYP   
5       

### Expected results:

```
MSZoning Street LotShape LandContour Utilities LotConfig LandSlope  \
Id
1          RL   PAVE      REG         LVL    ALLPUB    INSIDE       GTL
2          RL   PAVE      REG         LVL    ALLPUB       FR2       GTL
3          RL   PAVE      IR1         LVL    ALLPUB    INSIDE       GTL
4          RL   PAVE      IR1         LVL    ALLPUB    CORNER       GTL
5          RL   PAVE      IR1         LVL    ALLPUB       FR2       GTL
...       ...    ...      ...         ...       ...       ...       ...
1456       RL   PAVE      REG         LVL    ALLPUB    INSIDE       GTL
1457       RL   PAVE      REG         LVL    ALLPUB    INSIDE       GTL
1458       RL   PAVE      REG         LVL    ALLPUB    INSIDE       GTL
1459       RL   PAVE      REG         LVL    ALLPUB    INSIDE       GTL
1460       RL   PAVE      REG         LVL    ALLPUB    INSIDE       GTL

Neighborhood Condition1 Condition2  ... Electrical KitchenQual  \
Id                                       ...
1         COLLGCR       NORM       NORM  ...      SBRKR          GD
2 Veenker Feed Spring ... Sbrk TA
3         COLLGCR       NORM       NORM  ...      SBRKR          GD
4         CRAWFOR       NORM       NORM  ...      SBRKR          GD
5         NORIDGE       NORM       NORM  ...      SBRKR          GD
...           ...        ...        ...  ...        ...         ...
1456      GILBERT       NORM       NORM  ...      SBRKR          TA
1457 NWAMES NORM NORM ... SBRKR TA
1458      CRAWFOR       NORM       NORM  ...      SBRKR          GD
1459        NAMES       NORM       NORM  ...      FUSEA          GD
1460 Edwards Norm Norm ... Patience Ta

Functional GarageType GarageFinish GarageQual GarageCond PavedDrive  \
Id
1 TYP ATCHD ATCHD ATCHD AND
2 ATTCHD RFN ATCHD ATCHD AND
3 TYP ATCHD ATCHD ATCHD AND
4 TYP DETCHD UNF THE ONF THE
5 TYP ATCHD ATCHD ATCHD AND
...         ...        ...          ...        ...        ...        ...
1456 TYP ATCHD RFN ATCHD AT
1457 min1 Attchd UNF TA Y Y
1458 TYP ATCHD RFN ATCHD AT
1459 TYP ATCHD ATCHD THE AND
1460 TYP ATCHD FING THE

Saletype salecondition
Id
1          WD        NORMAL
2          WD        NORMAL
3          WD        NORMAL
4          WD       ABNORML
5          WD        NORMAL
...       ...           ...
1456       WD        NORMAL
1457       WD        NORMAL
1458       WD        NORMAL
1459       WD        NORMAL
1460       WD        NORMAL

[1338 rows x 38 columns]
```

### Step 4

After cleaning ```pd_dirty_data```, compare it with ```pd_data```. Do we need to make some changes to ```pd_data``` or/and ```pd_dirty_data``` to make a fair comparison? Implement ```compare_dataframes(pd_data, pd_dirty_data)``` function that will compare input ```DataFrames```.

In [151]:
import re
import pandas as pd
import numpy as np

def _normalize_str_series(s: pd.Series) -> pd.Series:
    s = s.astype(str)
    s = s.str.replace(r'[^A-Za-z0-9 ]+', '', regex=True)
    s = s.str.replace(r'\s+', ' ', regex=True).str.strip()
    s = s.str.upper()
    return s.where(~s.eq('NAN'), np.nan)

def compare_dataframes(pd_data, pd_dirty_data):
    common_idx = pd_data.index.intersection(pd_dirty_data.index)
    common_cols = pd_data.columns.intersection(pd_dirty_data.columns)

    a = pd_data.loc[common_idx, common_cols].copy()
    b = pd_dirty_data.loc[common_idx, common_cols].copy()

    obj_cols = [c for c in common_cols if a[c].dtype == 'object' or b[c].dtype == 'object']
    for c in obj_cols:
        a[c] = _normalize_str_series(a[c])
        b[c] = _normalize_str_series(b[c])

    equal_mask = (a == b) | (a.isna() & b.isna())

    pct_same = equal_mask.mean(axis=0) * 100
    pct_same = pct_same.round(6)
    pct_same.index.name = "(%) same"
    return pct_same




In [152]:
result = compare_dataframes(pd_data, pd_dirty_data)
print(result)


(%) same
MSZoning         100.0
Street           100.0
LotShape         100.0
LandContour      100.0
Utilities        100.0
LotConfig        100.0
LandSlope        100.0
Neighborhood     100.0
Condition1       100.0
Condition2       100.0
BldgType         100.0
HouseStyle       100.0
RoofStyle        100.0
RoofMatl         100.0
Exterior1st      100.0
Exterior2nd      100.0
MasVnrType       100.0
ExterQual        100.0
ExterCond        100.0
Foundation       100.0
BsmtQual         100.0
BsmtCond         100.0
BsmtExposure     100.0
BsmtFinType1     100.0
BsmtFinType2     100.0
Heating          100.0
HeatingQC        100.0
CentralAir       100.0
Electrical       100.0
KitchenQual      100.0
Functional       100.0
GarageType       100.0
GarageFinish     100.0
GarageQual       100.0
GarageCond       100.0
PavedDrive       100.0
SaleType         100.0
SaleCondition    100.0
dtype: float64


### Expected results:

```
(%) same
Mszoning 100,000000
Street         100.000000
Lotshepage 100.000000
LandContour    100.000000
Utilities      100.000000
LotConfig      100.000000
LandSlope      100.000000
Neighborhood   100.000000
Condition1 100.000000
Condition2     100.000000
BldgType       100.000000
HouseStyle      87.967115
ROOF STYLE 100.000000
RoofMatl       100.000000
Exterior1st    100.000000
Exterior2nd    100.000000
MasVnrType     100.000000
ExterQual      100.000000
ExterCond      100.000000
Foundation     100.000000
BsmtQual       100.000000
BsmtCond       100.000000
BsmtExposure   100.000000
BsmtFinType1   100.000000
BsmtFinType2   100.000000
Heating        100.000000
HeatingQC      100.000000
CentralAir     100.000000
Electrical     100.000000
KitchenQual    100.000000
Functional     100.000000
Garage type 100.000000
GarageFinish   100.000000
GarageQual     100.000000
GarageCond     100.000000
PavedDrive     100.000000
SaleType       100.000000
Salecondition 100.000000
```

# Good Job!